# Generated by Django 2.2 on 2019-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190905_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='finish_at',
            field=models.DateTimeField(default='', max_length=20, verbose_name='Время завершения'),
        ),
    ]
