# Generated by Django 2.2 on 2019-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190905_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='finish_at',
            field=models.DateField(blank=True, default='', max_length=20, null=True, verbose_name='Время завершения'),
        ),
    ]
