# Generated by Django 2.2 on 2019-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190905_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Подробное описание'),
        ),
    ]
